pipeline {
    agent any

    stages {

        stage('Get Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/salmakhaled-1/playwright-jenkins.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                python -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                playwright install
                '''
            }
        }

        stage('Run Tests') {
            steps {
                bat '''
                . venv/bin/activate
                pytest
                '''
            }
        }
    }
}
